name: Hedwig CGM Sync

on:
  push:
    branches: [ develop, main ]
  schedule:
    - cron: '*/5 * * * *' # 每 5 分钟自动运行
  workflow_dispatch: # 允许手动点击运行

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21' # 使用稳定的 Go 版本

    - name: Run Hedwig Backend
      env:
        CGM_USER: ${{ secrets.CGM_USER }}
        CGM_PWD: ${{ secrets.CGM_PWD }}
        BARK_KEY: ${{ secrets.BARK_KEY }}
      run: 
       cd backend
       go run cmd/hedwig/main.go

