name: Hedwig CGM Sync

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '*/5 * * * *' # 每5分钟云端自动跑一次
  workflow_dispatch: # 允许我们手动点击运行

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-packages: 'requests'

    - name: Run Hedwig Script
      env:
        CGM_USER: ${{ secrets.CGM_USER }}
        CGM_PWD: ${{ secrets.CGM_PWD }}
        BARK_KEY: ${{ secrets.BARK_KEY }}
      run: |
        if [ -f "main.py" ]; then
          python main.py
        elif [ -f "index.py" ]; then
          python index.py
        else
          python hedwig.py
        fi
