-- ============================================================
-- Hedwig 数据库建表脚本 (PostgreSQL)
-- ============================================================
-- 适配 Spring Boot 3 + JPA 后端，覆盖以下业务模块：
--   1. 用户信息
--   2. 设备厂商连接及用户关系
--   3. 被监控对象（CGM 佩戴者）
--   4. 血糖读数（来源设备信息）
--   5. Nightscout 远端配置（支持多个）
--   6. Nightscout 推送记录
--
-- 变更记录：
--   2025-03-20  v2  补齐 created_at/updated_at；修复 Entity-SQL 不一致；
--                    增加 gateway_users.nickname/status；优化索引；
--                    限制推送记录大字段长度。
-- ============================================================

-- ----------------------------------------------------------
-- 1. 用户信息
-- ----------------------------------------------------------
create table if not exists gateway_users (
    id              bigint generated by default as identity primary key,
    username        varchar(100)                not null,           -- 登录用户名，系统内唯一
    password_hash   varchar(255)                not null,           -- 密码哈希值（BCrypt），不保存明文
    nickname        varchar(100),                                   -- 用户昵称 / 显示名，前端展示用
    status          varchar(20)                 not null default 'ACTIVE', -- 账号状态：ACTIVE / DISABLED
    created_at      timestamp with time zone    not null default current_timestamp,
    updated_at      timestamp with time zone    not null default current_timestamp,

    constraint uk_gateway_users_username unique (username)
);

comment on table  gateway_users                    is '网关系统用户表';
comment on column gateway_users.id                 is '主键ID';
comment on column gateway_users.username           is '登录用户名，系统内唯一';
comment on column gateway_users.password_hash      is '密码哈希值，不保存明文密码';
comment on column gateway_users.nickname           is '用户昵称 / 显示名';
comment on column gateway_users.status             is '账号状态：ACTIVE-启用，DISABLED-禁用';
comment on column gateway_users.created_at         is '创建时间';
comment on column gateway_users.updated_at         is '最近修改时间';


-- ----------------------------------------------------------
-- 2. 设备厂商连接及用户关系
-- ----------------------------------------------------------
create table if not exists vendor_connections (
    id                bigint generated by default as identity primary key,
    gateway_user_id   bigint                      not null,         -- 关联 gateway_users.id
    vendor_type       varchar(32)                 not null,         -- 设备厂商类型：OTTAI / SISENSING
    access_token      varchar(2048)               not null,         -- 厂商接口访问令牌
    vendor_user_id    varchar(128),                                 -- 用户在厂商平台中的用户ID
    token_expires_at  timestamp with time zone,                     -- 访问令牌过期时间
    token_status      varchar(32)                 not null default 'ACTIVE', -- 令牌状态：ACTIVE / EXPIRING_SOON / EXPIRED
    last_synced_at    timestamp with time zone,                     -- 最近一次从厂商同步数据的时间
    created_at        timestamp with time zone    not null default current_timestamp,
    updated_at        timestamp with time zone    not null default current_timestamp,

    constraint fk_vendor_connections_gateway_user
        foreign key (gateway_user_id) references gateway_users (id)
        on delete cascade,
    constraint uk_vendor_connections_user_vendor
        unique (gateway_user_id, vendor_type)
);

comment on table  vendor_connections                            is '厂商连接表，保存 Hedwig 用户与 CGM 厂商账号/令牌的关系';
comment on column vendor_connections.id                         is '主键ID';
comment on column vendor_connections.gateway_user_id            is '关联 gateway_users.id';
comment on column vendor_connections.vendor_type                is '设备厂商类型，如 OTTAI、SISENSING';
comment on column vendor_connections.access_token               is '厂商接口访问令牌';
comment on column vendor_connections.vendor_user_id             is '用户在厂商平台中的用户ID';
comment on column vendor_connections.token_expires_at           is '访问令牌过期时间';
comment on column vendor_connections.token_status               is '令牌状态：ACTIVE-有效，EXPIRING_SOON-即将过期，EXPIRED-已过期';
comment on column vendor_connections.last_synced_at             is '最近一次从厂商同步数据的时间';
comment on column vendor_connections.created_at                 is '创建时间';
comment on column vendor_connections.updated_at                 is '最近修改时间';

-- 按用户查询其全部厂商连接
create index if not exists idx_vendor_connections_gateway_user_id
    on vendor_connections (gateway_user_id);

-- 按令牌状态查询（定时刷新/告警）
create index if not exists idx_vendor_connections_token_status
    on vendor_connections (token_status);


-- ----------------------------------------------------------
-- 3. 被监控对象（CGM 佩戴者）
-- ----------------------------------------------------------
create table if not exists monitored_subjects (
    id                     bigint generated by default as identity primary key,
    -- 允许为空：原始厂商连接删除后仍保留历史被监控对象和血糖数据
    vendor_connection_id   bigint,                                  -- 关联 vendor_connections.id，可空
    vendor_subject_id      varchar(128)             not null,       -- 被监控对象在厂商平台中的唯一ID
    vendor_device_id       varchar(128),                            -- 被监控对象当前使用的设备ID
    display_name           varchar(100),                            -- 被监控对象显示名称
    is_active              boolean                  not null default true,  -- 是否启用监控
    sensor_expires_at      timestamp with time zone,                -- 传感器预计失效时间
    created_at             timestamp with time zone not null default current_timestamp,
    updated_at             timestamp with time zone not null default current_timestamp,

    constraint fk_monitored_subjects_vendor_connection
        foreign key (vendor_connection_id) references vendor_connections (id)
        on delete set null,
    constraint uk_monitored_subjects_connection_subject
        unique (vendor_connection_id, vendor_subject_id)
);

comment on table  monitored_subjects                                  is '被监控对象表，保存厂商平台中的监护对象及其设备信息';
comment on column monitored_subjects.id                               is '主键ID';
comment on column monitored_subjects.vendor_connection_id             is '关联 vendor_connections.id，为空表示原连接已移除';
comment on column monitored_subjects.vendor_subject_id                is '被监控对象在厂商平台中的唯一ID';
comment on column monitored_subjects.vendor_device_id                 is '被监控对象当前使用的设备ID';
comment on column monitored_subjects.display_name                     is '被监控对象显示名称';
comment on column monitored_subjects.is_active                        is '是否启用监控';
comment on column monitored_subjects.sensor_expires_at                is '传感器预计失效时间';
comment on column monitored_subjects.created_at                       is '创建时间';
comment on column monitored_subjects.updated_at                       is '最近修改时间';

-- 按厂商连接查询其下所有被监控对象
create index if not exists idx_monitored_subjects_vendor_connection_id
    on monitored_subjects (vendor_connection_id);

-- 按设备ID快速定位
create index if not exists idx_monitored_subjects_vendor_device_id
    on monitored_subjects (vendor_device_id);


-- ----------------------------------------------------------
-- 4. 血糖读数（来源设备信息）
-- ----------------------------------------------------------
create table if not exists glucose_readings (
    id                      bigint generated by default as identity primary key,
    monitored_subject_id    bigint                    not null,     -- 关联 monitored_subjects.id
    glucose_mmol            numeric(6, 2)             not null,     -- 血糖值 mmol/L
    glucose_mgdl            numeric(6, 2)             not null,     -- 血糖值 mg/dL
    trend_direction         varchar(32)               not null default 'NONE', -- 血糖趋势方向
    reading_time            timestamp with time zone  not null,     -- 读数产生时间（设备采集时间）
    -- 兼容当前单 Nightscout 目标逻辑；升级为多目标后以 nightscout_push_records 为准
    pushed_to_nightscout    boolean                   not null default false,
    created_at              timestamp with time zone  not null default current_timestamp,

    constraint fk_glucose_readings_monitored_subject
        foreign key (monitored_subject_id) references monitored_subjects (id)
        on delete cascade,
    -- 同一被监控对象 + 同一采集时间 = 唯一读数，防止重复入库
    constraint uk_glucose_readings_subject_time
        unique (monitored_subject_id, reading_time)
);

comment on table  glucose_readings                                 is '血糖读数表，保存每次采集到的血糖数据';
comment on column glucose_readings.id                              is '主键ID';
comment on column glucose_readings.monitored_subject_id            is '关联 monitored_subjects.id';
comment on column glucose_readings.glucose_mmol                    is '血糖值，单位 mmol/L';
comment on column glucose_readings.glucose_mgdl                    is '血糖值，单位 mg/dL';
comment on column glucose_readings.trend_direction                 is '血糖趋势方向：DOUBLE_UP/SINGLE_UP/FORTY_FIVE_UP/FLAT/FORTY_FIVE_DOWN/SINGLE_DOWN/DOUBLE_DOWN/NONE';
comment on column glucose_readings.reading_time                    is '读数产生时间（设备端采集时间）';
comment on column glucose_readings.pushed_to_nightscout            is '是否已推送到 Nightscout（兼容单目标实现，多目标后以 push_records 为准）';
comment on column glucose_readings.created_at                      is '入库时间（区别于 reading_time 的设备采集时间）';

-- 查询某对象某时间段的血糖数据（高频查询）
create index if not exists idx_glucose_readings_subject_time
    on glucose_readings (monitored_subject_id, reading_time desc);

-- 查询待推送血糖数据
create index if not exists idx_glucose_readings_pending_push
    on glucose_readings (pushed_to_nightscout) where pushed_to_nightscout = false;


-- ----------------------------------------------------------
-- 5. Nightscout 远端配置（支持多个）
-- ----------------------------------------------------------
create table if not exists nightscout_targets (
    id                      bigint generated by default as identity primary key,
    gateway_user_id         bigint                    not null,     -- 关联 gateway_users.id
    -- 为空时推送当前用户的全部被监控对象；不为空时只推指定对象
    monitored_subject_id    bigint,                                 -- 关联 monitored_subjects.id，可空
    name                    varchar(100)              not null,     -- Nightscout 目标名称，用户内唯一
    base_url                varchar(512)              not null,     -- Nightscout 服务地址
    api_secret_sha1         char(40)                  not null,     -- Nightscout API Secret 的 SHA-1 值（40位十六进制）
    api_secret_hint         varchar(32),                            -- API Secret 提示信息（如后四位），帮助用户识别
    status                  varchar(20)               not null default 'ACTIVE', -- 目标状态：ACTIVE / DISABLED
    is_default              boolean                   not null default false,    -- 是否默认推送目标
    last_push_at            timestamp with time zone,               -- 最近一次发起推送的时间
    last_success_at         timestamp with time zone,               -- 最近一次推送成功时间
    last_error_message      varchar(1000),                          -- 最近一次推送失败信息
    created_at              timestamp with time zone  not null default current_timestamp,
    updated_at              timestamp with time zone  not null default current_timestamp,

    constraint fk_nightscout_targets_gateway_user
        foreign key (gateway_user_id) references gateway_users (id)
        on delete cascade,
    constraint fk_nightscout_targets_monitored_subject
        foreign key (monitored_subject_id) references monitored_subjects (id)
        on delete set null,
    -- 同一用户下目标名称唯一
    constraint uk_nightscout_targets_user_name
        unique (gateway_user_id, name)
);

comment on table  nightscout_targets                                  is 'Nightscout 远端配置表，支持每个用户配置多个推送目标';
comment on column nightscout_targets.id                               is '主键ID';
comment on column nightscout_targets.gateway_user_id                  is '关联 gateway_users.id';
comment on column nightscout_targets.monitored_subject_id             is '关联 monitored_subjects.id，为空表示推送该用户全部对象';
comment on column nightscout_targets.name                             is 'Nightscout 目标名称，用户内唯一';
comment on column nightscout_targets.base_url                         is 'Nightscout 服务地址';
comment on column nightscout_targets.api_secret_sha1                  is 'Nightscout API Secret 的 SHA-1 值（40位十六进制）';
comment on column nightscout_targets.api_secret_hint                  is 'API Secret 提示信息，如后四位或备注';
comment on column nightscout_targets.status                           is '目标状态：ACTIVE-启用，DISABLED-停用';
comment on column nightscout_targets.is_default                       is '是否默认推送目标';
comment on column nightscout_targets.last_push_at                     is '最近一次发起推送的时间';
comment on column nightscout_targets.last_success_at                  is '最近一次推送成功时间';
comment on column nightscout_targets.last_error_message               is '最近一次推送失败信息';
comment on column nightscout_targets.created_at                       is '创建时间';
comment on column nightscout_targets.updated_at                       is '最近修改时间';

-- 按用户查询其全部 Nightscout 配置
create index if not exists idx_nightscout_targets_gateway_user_id
    on nightscout_targets (gateway_user_id);

-- 按被监控对象查询关联的推送目标
create index if not exists idx_nightscout_targets_monitored_subject_id
    on nightscout_targets (monitored_subject_id);

-- 按状态过滤启用的目标（调度推送时使用）
create index if not exists idx_nightscout_targets_status
    on nightscout_targets (status);


-- ----------------------------------------------------------
-- 6. Nightscout 推送记录
-- ----------------------------------------------------------
create table if not exists nightscout_push_records (
    id                      bigint generated by default as identity primary key,
    nightscout_target_id    bigint                    not null,     -- 关联 nightscout_targets.id
    glucose_reading_id      bigint                    not null,     -- 关联 glucose_readings.id
    gateway_user_id         bigint                    not null,     -- 冗余：所属用户ID，便于按用户维度查询
    monitored_subject_id    bigint                    not null,     -- 冗余：被监控对象ID，便于按对象维度查询
    push_status             varchar(20)               not null default 'PENDING', -- 推送状态：PENDING / SUCCESS / FAILED
    attempt_count           integer                   not null default 0,         -- 累计推送尝试次数
    last_attempt_at         timestamp with time zone,               -- 最近一次尝试推送时间
    success_at              timestamp with time zone,               -- 推送成功时间
    next_retry_at           timestamp with time zone,               -- 下一次重试时间（用于调度器捞取）
    http_status             integer,                                -- Nightscout 接口响应状态码
    request_payload         varchar(4000),                          -- 推送请求报文（限制长度防膨胀）
    response_body           varchar(4000),                          -- Nightscout 返回内容（限制长度防膨胀）
    error_message           varchar(1000),                          -- 错误信息
    created_at              timestamp with time zone  not null default current_timestamp,
    updated_at              timestamp with time zone  not null default current_timestamp,

    constraint fk_push_records_target
        foreign key (nightscout_target_id) references nightscout_targets (id)
        on delete cascade,
    constraint fk_push_records_reading
        foreign key (glucose_reading_id) references glucose_readings (id)
        on delete cascade,
    constraint fk_push_records_gateway_user
        foreign key (gateway_user_id) references gateway_users (id)
        on delete cascade,
    constraint fk_push_records_monitored_subject
        foreign key (monitored_subject_id) references monitored_subjects (id)
        on delete cascade,
    -- 同一目标 + 同一血糖读数 = 唯一推送记录
    constraint uk_push_records_target_reading
        unique (nightscout_target_id, glucose_reading_id)
);

comment on table  nightscout_push_records                                is 'Nightscout 推送记录表，记录每条血糖数据向每个目标的推送结果';
comment on column nightscout_push_records.id                             is '主键ID';
comment on column nightscout_push_records.nightscout_target_id           is '关联 nightscout_targets.id';
comment on column nightscout_push_records.glucose_reading_id             is '关联 glucose_readings.id';
comment on column nightscout_push_records.gateway_user_id                is '冗余保存所属用户ID，便于按用户维度查询和统计';
comment on column nightscout_push_records.monitored_subject_id           is '冗余保存被监控对象ID，便于按对象维度查询和统计';
comment on column nightscout_push_records.push_status                    is '推送状态：PENDING-待推送，SUCCESS-成功，FAILED-失败';
comment on column nightscout_push_records.attempt_count                  is '累计推送尝试次数';
comment on column nightscout_push_records.last_attempt_at                is '最近一次尝试推送时间';
comment on column nightscout_push_records.success_at                     is '推送成功时间';
comment on column nightscout_push_records.next_retry_at                  is '下一次重试时间，调度器按此字段捞取待重试记录';
comment on column nightscout_push_records.http_status                    is 'Nightscout 接口响应 HTTP 状态码';
comment on column nightscout_push_records.request_payload                is '推送请求报文，便于排查问题（限4000字符）';
comment on column nightscout_push_records.response_body                  is 'Nightscout 返回内容（限4000字符）';
comment on column nightscout_push_records.error_message                  is '错误信息';
comment on column nightscout_push_records.created_at                     is '创建时间';
comment on column nightscout_push_records.updated_at                     is '最近修改时间';

-- 按用户 + 推送状态查询（用户维度统计/重推）
create index if not exists idx_push_records_user_status
    on nightscout_push_records (gateway_user_id, push_status);

-- 按被监控对象 + 推送状态查询
create index if not exists idx_push_records_subject_status
    on nightscout_push_records (monitored_subject_id, push_status);

-- 重试调度器：按状态 + 下次重试时间捞取待重试记录
create index if not exists idx_push_records_pending_retry
    on nightscout_push_records (push_status, next_retry_at)
    where push_status in ('PENDING', 'FAILED');

-- 按目标查询推送记录
create index if not exists idx_push_records_target_id
    on nightscout_push_records (nightscout_target_id);